menu:
  首页: /wechat-blog
  文章归档: /wechat-blog/archives
  关于: /wechat-blog/about

excerpt_link: 阅读全文 >

google_analytics: UA-35975331-1

rss: /wechat-blog/atom.xml

comment_provider: duoshuo
# Duoshuo comment
duoshuo:
  short_name: lurongkai
